// <auto-generated />
namespace PolyclinicProject.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Crear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Crear));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081654396_Crear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
